import type { ClubConfig } from "@/lib/club/types";

export const DEFAULT_CLUB_CONFIG: ClubConfig = {
  version: 1,
  iqdPerPoint: 5000,
  reviewBonus: 50,
  referralBonus: 200,
  birthdayBonus: 100,
  doublePointsActive: false,
  triplePointsActive: false,
  streakMonthsRequired: 5,
  passportRewardPoints: 300,
  tiers: [
    {
      id: "muse",
      nameEn: "Muse",
      nameAr: "ميوز",
      minPoints: 0,
      maxPoints: 499,
      icon: "muse",
      privilegesEn: ["Bonus Points", "Club updates"],
      privilegesAr: ["نقاط إضافية", "تحديثات النادي"],
      birthdayGiftEn: "Bonus Points",
      birthdayGiftAr: "نقاط إضافية",
    },
    {
      id: "glow",
      nameEn: "Glow",
      nameAr: "جلو",
      minPoints: 500,
      maxPoints: 1499,
      icon: "glow",
      privilegesEn: ["Exclusive Coupon", "Early Access"],
      privilegesAr: ["قسيمة حصرية", "وصول مبكر"],
      birthdayGiftEn: "Exclusive Coupon",
      birthdayGiftAr: "قسيمة حصرية",
    },
    {
      id: "signature",
      nameEn: "Signature",
      nameAr: "سيغنتشر",
      minPoints: 1500,
      maxPoints: 2999,
      icon: "signature",
      privilegesEn: ["Beauty Gift", "Double Points events"],
      privilegesAr: ["هدية جمال", "فعاليات النقاط المضاعفة"],
      birthdayGiftEn: "Beauty Gift",
      birthdayGiftAr: "هدية جمال",
    },
    {
      id: "prive",
      nameEn: "Privé",
      nameAr: "بريفيه",
      minPoints: 3000,
      maxPoints: null,
      icon: "prive",
      privilegesEn: [
        "Priority Access",
        "Exclusive Gifts",
        "Private Offers",
        "Beauty Concierge",
      ],
      privilegesAr: [
        "أولوية الوصول",
        "هدايا حصرية",
        "عروض خاصة",
        "كونسيرج الجمال",
      ],
      birthdayGiftEn: "Premium Beauty Gift",
      birthdayGiftAr: "هدية جمال فاخرة",
    },
  ],
  rewards: [
    {
      id: "r300",
      cost: 300,
      titleEn: "5,000 IQD OFF",
      titleAr: "خصم 5,000 د.ع",
      subtitleEn: "On your next order",
      subtitleAr: "على طلبكِ القادم",
      cta: "redeem",
    },
    {
      id: "r500",
      cost: 500,
      titleEn: "10,000 IQD OFF",
      titleAr: "خصم 10,000 د.ع",
      subtitleEn: "On orders over 50,000 IQD",
      subtitleAr: "على طلبات فوق 50,000 د.ع",
      cta: "redeem",
    },
    {
      id: "r750",
      cost: 750,
      titleEn: "FREE DELIVERY",
      titleAr: "توصيل مجاني",
      subtitleEn: "Baghdad & selected cities",
      subtitleAr: "بغداد ومدن مختارة",
      cta: "redeem",
    },
    {
      id: "r1000",
      cost: 1000,
      titleEn: "BEAUTY GIFT",
      titleAr: "هدية جمال",
      subtitleEn: "A curated surprise from VELORA",
      subtitleAr: "مفاجأة مختارة من فيلورا",
      cta: "reveal",
    },
    {
      id: "r2000",
      cost: 2000,
      titleEn: "SIGNATURE BEAUTY BOX",
      titleAr: "صندوق سيغنتشر",
      subtitleEn: "Limited seasonal edit",
      subtitleAr: "إصدار موسمي محدود",
      cta: "unlock",
    },
  ],
  privileges: [
    {
      id: "early",
      icon: "key",
      titleEn: "Early Access",
      titleAr: "وصول مبكر",
      bodyEn: "Discover new arrivals before everyone else.",
      bodyAr: "اكتشفي الجديد قبل الجميع.",
    },
    {
      id: "birthday",
      icon: "gift",
      titleEn: "Birthday Privilege",
      titleAr: "امتياز عيد الميلاد",
      bodyEn: "A special gift from VELORA.",
      bodyAr: "هدية خاصة من فيلورا.",
    },
    {
      id: "double",
      icon: "spark",
      titleEn: "Double Points",
      titleAr: "نقاط مضاعفة",
      bodyEn: "Earn more during exclusive VELORA events.",
      bodyAr: "اجمعي المزيد في فعاليات فيلورا الحصرية.",
    },
    {
      id: "gifts",
      icon: "diamond",
      titleEn: "Beauty Gifts",
      titleAr: "هدايا الجمال",
      bodyEn: "Unlock curated gifts with your membership.",
      bodyAr: "افتحي هدايا مختارة بعضويتكِ.",
    },
    {
      id: "delivery",
      icon: "delivery",
      titleEn: "Free Delivery",
      titleAr: "توصيل مجاني",
      bodyEn: "Available at selected membership levels.",
      bodyAr: "متاح في مستويات عضوية محددة.",
    },
    {
      id: "offers",
      icon: "link",
      titleEn: "Private Offers",
      titleAr: "عروض خاصة",
      bodyEn: "Exclusive offers selected for you.",
      bodyAr: "عروض حصرية مختارة لكِ.",
    },
  ],
  earnCards: [
    {
      id: "shop",
      icon: "bag",
      titleEn: "SHOP",
      titleAr: "تسوّقي",
      bodyEn: "Earn points with every order.",
      bodyAr: "اجمعي نقاطاً مع كل طلب.",
    },
    {
      id: "review",
      icon: "star",
      titleEn: "REVIEW",
      titleAr: "راجعي",
      bodyEn: "Share your experience.",
      bodyAr: "شاركي تجربتكِ.",
    },
    {
      id: "refer",
      icon: "link",
      titleEn: "REFER",
      titleAr: "ادعِي",
      bodyEn: "Invite a friend.",
      bodyAr: "ادعِ صديقة.",
    },
    {
      id: "bday",
      icon: "gift",
      titleEn: "BIRTHDAY",
      titleAr: "عيد الميلاد",
      bodyEn: "Receive your birthday reward.",
      bodyAr: "احصلي على مكافأة عيد ميلادكِ.",
    },
    {
      id: "events",
      icon: "spark",
      titleEn: "SPECIAL EVENTS",
      titleAr: "فعاليات خاصة",
      bodyEn: "Earn double or triple points.",
      bodyAr: "اجمعي نقاطاً مضاعفة أو ثلاثية.",
    },
  ],
  passportBrands: [
    { id: "loreal", name: "L’Oréal" },
    { id: "vichy", name: "Vichy" },
    { id: "lrp", name: "La Roche-Posay" },
    { id: "mac", name: "MAC" },
    { id: "nars", name: "NARS" },
  ],
  mysteryPool: [
    {
      id: "m1",
      titleEn: "15% OFF YOUR NEXT ORDER",
      titleAr: "خصم 15% على طلبكِ القادم",
    },
    {
      id: "m2",
      titleEn: "+500 V•POINTS",
      titleAr: "+500 نقطة V•POINTS",
    },
    {
      id: "m3",
      titleEn: "BEAUTY GIFT UNLOCKED",
      titleAr: "تم فتح هدية جمال",
    },
    {
      id: "m4",
      titleEn: "FREE DELIVERY",
      titleAr: "توصيل مجاني",
    },
  ],
  priveBenefitsEn: [
    "Priority Access",
    "Exclusive Gifts",
    "Private Offers",
    "Early Product Access",
    "Premium Birthday Gift",
    "Beauty Concierge",
  ],
  priveBenefitsAr: [
    "أولوية الوصول",
    "هدايا حصرية",
    "عروض خاصة",
    "وصول مبكر للمنتجات",
    "هدية عيد ميلاد فاخرة",
    "كونسيرج الجمال",
  ],
  conciergeWhatsApp: process.env.WHATSAPP_COMPANY_PHONE?.trim() || "9647810115755",
};
