import {
  LayoutDashboard,
  ShoppingBag,
  Package,
  Users,
  Truck,
  CreditCard,
  MessageCircle,
  Warehouse,
  UserCog,
  Building2,
  Megaphone,
  Gem,
  ChartColumn,
  FileText,
  Settings,
  Search,
  Bell,
  Plus,
  ChevronDown,
  MoreHorizontal,
  Check,
  X,
  Copy,
  Printer,
  ExternalLink,
  ArrowUpRight,
  ArrowDownRight,
  Minus,
  Filter,
  PanelLeft,
  Store,
  LogOut,
  Menu,
  CalendarCheck,
  Wallet,
  Images,
  Sparkles,
  TrendingUp,
  Factory,
  Ship,
  Receipt,
  BadgeDollarSign,
  Landmark,
  TriangleAlert,
  Tags,
  type LucideIcon,
} from "lucide-react";
import type { AdminNavId } from "@/lib/admin/nav";
import type { OrderStatusTone } from "@/lib/order-types";

const NAV_ICONS: Record<AdminNavId, LucideIcon> = {
  overview: LayoutDashboard,
  ai: Sparkles,
  sales: TrendingUp,
  orders: ShoppingBag,
  products: Package,
  inventory: Warehouse,
  brands: Tags,
  suppliers: Factory,
  imports: Ship,
  expenses: Receipt,
  payroll: Wallet,
  profitability: BadgeDollarSign,
  finance: Landmark,
  analytics: ChartColumn,
  reports: FileText,
  alerts: TriangleAlert,
  customers: Users,
  shipping: Truck,
  payments: CreditCard,
  whatsapp: MessageCircle,
  employees: UserCog,
  branches: Building2,
  marketing: Megaphone,
  notifications: Bell,
  homepage: Images,
  club: Gem,
  "my-velora": Sparkles,
  settings: Settings,
};

export function AdminNavIcon({
  id,
  className = "size-4",
  strokeWidth = 1.6,
}: {
  id: AdminNavId;
  className?: string;
  strokeWidth?: number;
}) {
  const Icon = NAV_ICONS[id];
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden />;
}

export {
  Search,
  Bell,
  Plus,
  ChevronDown,
  MoreHorizontal,
  Check,
  X,
  Copy,
  Printer,
  ExternalLink,
  ArrowUpRight,
  ArrowDownRight,
  Minus,
  Filter,
  PanelLeft,
  Store,
  LogOut,
  Menu,
  LayoutDashboard,
  ShoppingBag,
  Package,
  Users,
  Truck,
  CreditCard,
  MessageCircle,
  Warehouse,
  UserCog,
  Building2,
  Megaphone,
  ChartColumn,
  FileText,
  Settings,
  CalendarCheck,
  Wallet,
  Gem,
};

export type { LucideIcon };

export const TONE_BADGE: Record<OrderStatusTone, string> = {
  neutral: "bg-[var(--admin-surface-soft)] text-[var(--admin-text-secondary)]",
  info: "bg-[var(--admin-info-bg)] text-[var(--admin-info)]",
  progress: "bg-[var(--admin-warning-bg)] text-[var(--admin-warning)]",
  shipping: "bg-[var(--admin-shipping-bg)] text-[var(--admin-shipping)]",
  success: "bg-[var(--admin-success-bg)] text-[var(--admin-success)]",
  warning: "bg-[var(--admin-warning-bg)] text-[var(--admin-warning)]",
  danger: "bg-[var(--admin-danger-bg)] text-[var(--admin-danger)]",
};
