import type { HomeHeroConfig } from "@/lib/home/types";

export const DEFAULT_HOME_HERO: HomeHeroConfig = {
  version: 1,
  autoplayMs: 5500,
  slides: [
    {
      id: "signature",
      enabled: true,
      headlineAr: "لأن جمالك يستحق الأفضل",
      headlineEn: "Because your beauty deserves the best",
      bodyAr:
        "علامات عالمية أصلية تلبي كل احتياجاتك بأناقة وجودة استثنائية.",
      bodyEn:
        "Authentic global houses curated for elegance and exceptional quality.",
      ctaAr: "تسوقي الآن",
      ctaEn: "Shop now",
      href: "/shop",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center center",
      textAlign: "start",
      overlay: "soft",
    },
    {
      id: "skincare",
      enabled: true,
      headlineAr: "بشرتك تستحق عناية استثنائية",
      headlineEn: "Your skin deserves exceptional care",
      bodyAr: "اكتشفي روتينك المثالي للعناية اليومية.",
      bodyEn: "Discover your ideal daily skincare ritual.",
      ctaAr: "اكتشفي العناية",
      ctaEn: "Explore skincare",
      href: "/shop?category=skincare",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center 55%",
      textAlign: "start",
      overlay: "soft",
    },
    {
      id: "makeup",
      enabled: true,
      headlineAr: "إطلالتك تبدأ من هنا",
      headlineEn: "Your look begins here",
      bodyAr: "مختارات من أشهر علامات المكياج العالمية.",
      bodyEn: "A curated edit of the world’s most loved makeup houses.",
      ctaAr: "اكتشفي المكياج",
      ctaEn: "Explore makeup",
      href: "/shop?category=makeup",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "right center",
      textAlign: "start",
      overlay: "medium",
    },
    {
      id: "new",
      enabled: true,
      headlineAr: "وصل حديثاً ✦",
      headlineEn: "Just arrived ✦",
      bodyAr: "أحدث المنتجات العالمية وصلت الآن إلى VELORA.",
      bodyEn: "The newest global arrivals are here at VELORA.",
      ctaAr: "اكتشفي الجديد",
      ctaEn: "See what’s new",
      href: "/shop",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center center",
      textAlign: "start",
      overlay: "strong",
    },
  ],
};
