import type { HomeCategoryConfig, HomeHeroConfig, HomePromoConfig } from "@/lib/home/types";

export const DEFAULT_HOME_CATEGORIES: HomeCategoryConfig = {
  version: 1,
  cards: [
    {
      id: "skincare",
      slug: "skincare",
      enabled: true,
      titleAr: "العناية بالبشرة",
      titleEn: "Skincare",
      ctaAr: "استكشفي",
      ctaEn: "Explore",
      href: "/shop?category=skincare",
      imageUrl: "/brand/categories/skincare.png",
      objectPosition: "center center",
    },
    {
      id: "makeup",
      slug: "makeup",
      enabled: true,
      titleAr: "المكياج",
      titleEn: "Makeup",
      ctaAr: "استكشفي",
      ctaEn: "Explore",
      href: "/shop?category=makeup",
      imageUrl: "/brand/categories/makeup.png",
      objectPosition: "center center",
    },
    {
      id: "hair-care",
      slug: "hair-care",
      enabled: true,
      titleAr: "العناية بالشعر",
      titleEn: "Hair care",
      ctaAr: "استكشفي",
      ctaEn: "Explore",
      href: "/shop?category=hair-care",
      imageUrl: "/brand/categories/skincare.png",
      objectPosition: "center center",
    },
    {
      id: "body-care",
      slug: "body-care",
      enabled: true,
      titleAr: "العناية بالجسم",
      titleEn: "Body care",
      ctaAr: "استكشفي",
      ctaEn: "Explore",
      href: "/shop?category=body-care",
      imageUrl: "/brand/categories/makeup.png",
      objectPosition: "center center",
    },
  ],
};

export const DEFAULT_HOME_PROMO: HomePromoConfig = {
  version: 1,
  enabled: true,
  headlineAr: "وصل حديثاً ✦",
  headlineEn: "Just arrived ✦",
  bodyAr:
    "اكتشفي أحدث الصيحات والمنتجات العالمية التي وصلت للتو إلى VELORA",
  bodyEn:
    "Discover the newest global trends and products just arrived at VELORA",
  ctaAr: "استكشفي الآن",
  ctaEn: "Explore now",
  href: "/shop",
  imageUrl: "/brand/categories/promo-gift.png",
  objectPosition: "left center",
};

export const DEFAULT_HOME_HERO: HomeHeroConfig = {
  version: 1,
  autoplayMs: 5500,
  slides: [
    {
      id: "signature",
      enabled: true,
      headlineAr: "لأن جمالك يستحق الأفضل",
      headlineEn: "Because your beauty deserves the best",
      bodyAr:
        "علامات عالمية أصلية تلبي كل احتياجاتك بأناقة وجودة استثنائية.",
      bodyEn:
        "Authentic global houses curated for elegance and exceptional quality.",
      ctaAr: "تسوقي الآن",
      ctaEn: "Shop now",
      href: "/shop",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center center",
      textAlign: "start",
      overlay: "soft",
    },
    {
      id: "skincare",
      enabled: true,
      headlineAr: "بشرتك تستحق عناية استثنائية",
      headlineEn: "Your skin deserves exceptional care",
      bodyAr: "اكتشفي روتينك المثالي للعناية اليومية.",
      bodyEn: "Discover your ideal daily skincare ritual.",
      ctaAr: "اكتشفي العناية",
      ctaEn: "Explore skincare",
      href: "/shop?category=skincare",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center 55%",
      textAlign: "start",
      overlay: "soft",
    },
    {
      id: "makeup",
      enabled: true,
      headlineAr: "إطلالتك تبدأ من هنا",
      headlineEn: "Your look begins here",
      bodyAr: "مختارات من أشهر علامات المكياج العالمية.",
      bodyEn: "A curated edit of the world’s most loved makeup houses.",
      ctaAr: "اكتشفي المكياج",
      ctaEn: "Explore makeup",
      href: "/shop?category=makeup",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "right center",
      textAlign: "start",
      overlay: "medium",
    },
    {
      id: "new",
      enabled: true,
      headlineAr: "وصل حديثاً ✦",
      headlineEn: "Just arrived ✦",
      bodyAr: "أحدث المنتجات العالمية وصلت الآن إلى VELORA.",
      bodyEn: "The newest global arrivals are here at VELORA.",
      ctaAr: "اكتشفي الجديد",
      ctaEn: "See what’s new",
      href: "/shop",
      imageUrl: "/brand/hero-banner.png",
      imageUrlMobile: "/brand/hero-banner.png",
      objectPosition: "center center",
      textAlign: "start",
      overlay: "strong",
    },
  ],
};
